name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        cmake-version: [3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Eigen
      run: |
        sudo apt-get update
        sudo apt-get install -y sudo apt install libeigen3-dev libyaml-cpp-dev
    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_TESTING=ON
        make
        make test